services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=NotPassword@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  miniapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miniapi
    depends_on:
      - sqlserver
    ports:
      - "5027:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiniAPI;User Id=sa;Password=NotPassword@123;TrustServerCertificate=True;
  
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: dockerfile.dev
    container_name: frontend
    ports:
      - "3000:5173"
    working_dir: /react-app
    volumes:
      - ./FrontEnd:/react-app
      - /react-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - miniapi

volumes:
  sqlvolume: